# Generated by Django 3.1 on 2022-07-20 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20220719_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='media/item_pics/%Y/%m/%d')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='market.item')),
            ],
        ),
    ]
