# Generated by Django 3.1 on 2022-07-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_itemgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemgallery',
            options={'verbose_name': 'Item Gallery', 'verbose_name_plural': 'Item Gallery'},
        ),
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(blank=True, upload_to='media/item_pics/%Y/%m/%d'),
        ),
    ]
