# Generated by Django 3.1 on 2022-07-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20220720_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image1',
            field=models.ImageField(default='media/images.png', upload_to='media/item_pics/%Y/%m/%d'),
        ),
    ]
