# Generated by Django 3.1 on 2022-07-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20220725_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='image1',
            field=models.ImageField(default='default_image.png', upload_to='media/item_pics/%Y/%m/%d'),
        ),
    ]
