# Generated by Django 3.1 on 2022-08-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_saveditem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saveditem',
            unique_together=set(),
        ),
    ]
