# Generated by Django 3.1 on 2022-08-01 06:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0008_auto_20220801_0608'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saveditem',
            unique_together={('user', 'item')},
        ),
    ]
