# Generated by Django 3.1 on 2022-08-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
